# -*- coding: utf-8 -*-
"""Parkingutilization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12YaFV59wOwelFzOcF5ryxxd2LP3b4eXT
"""

import pandas as pd

# Loading the dataset
data = pd.read_csv("parking_data.csv", encoding="utf-8")
print(data.head(499))

#Converting date columns to datetime:
data['Entry_Time'] = pd.to_datetime(data['Entry_Time'])
data['Exit_Time'] = pd.to_datetime(data['Exit_Time'])

# Calculate the parking duration for each row
data['Duration'] = (data['Exit_Time'] - data['Entry_Time']).dt.total_seconds() / 3600  # duration in hours

print(data.head(300))

#Calculating the average parking duration:
avg_duration = data['Duration'].mean()
print(f"Average Parking Duration: {avg_duration:.2f} hours")

# Utilization rate for each parking spot (percentage of time it was occupied)
parking_utilization = data.groupby('Parking_Spot_ID')['Duration'].sum() / (data['Exit_Time'].max() - data['Entry_Time'].min()).total_seconds() * 100
print(parking_utilization)

# Peak hours of parking usage
data['Hour'] = data['Entry_Time'].dt.hour
peak_hours = data.groupby('Hour').size()
print("Peak Hours of Parking Usage:")
print(peak_hours)

data_cleaned = data.dropna(subset=['Entry_Time', 'Exit_Time'])

# Filter parking spots with high usage (e.g., spots that were used for more than 10 hours)
high_usage_spots = data.groupby('Parking_Spot_ID')['Duration'].sum()
high_usage_spots = high_usage_spots[high_usage_spots > 10]
print(f"Parking Spots with High Usage: {high_usage_spots}")

import matplotlib.pyplot as plt

# Plot parking utilization
plt.figure(figsize=(10, 6))
parking_utilization.plot(kind='bar')
plt.title('Parking Spot Utilization')
plt.xlabel('Parking Spot ID')
plt.ylabel('Utilization (%)')
plt.show()

# Plot peak usage hours
plt.figure(figsize=(10, 6))
peak_hours.plot(kind='bar')
plt.title('Peak Parking Usage by Hour')
plt.xlabel('Hour of Day')
plt.ylabel('Number of Cars')
plt.show()

